version: '3.8'

services:
  meu_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=production
